export const SET_CURRENT_SCHEDULE = 'SET_CURRENT_SCHEDULE'
export const FETCH_SCHEDULE = 'FETCH_SCHEDULE'
export const FETCHED_SCHEDULE = 'FETCHED_SCHEDULE'

export const SELECT_STATION = 'SELECT_STATION'
export const SET_CURRENT_STATION = 'SET_CURRENT_STATION'

export const FETCH_STATIONS = 'FETCH_STATIONS'
export const FETCHED_STATIONS = 'FETCHED_STATIONS'

export const FILTER_BY_DESTINATION = 'FILTER_BY_DESTINATION'
